# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: Build and test
on: [push, pull_request]
jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: extract secrets
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
        run: |
          echo "$GOOGLE_SERVICES_JSON" | base64 -d > ./app/google-services.json
          echo "$GOOGLE_MAPS_KEY" | base64 -d > ./app/src/main/res/values/google_maps_key.xml

      - name: build
        run: ./gradlew :clean :app:assembleDebug
      
      - name: run tests
        run: ./gradlew :app:testDebug || echo tests failed

      - name: save APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/

      - name: save test reports
        uses: actions/upload-artifact@v1
        with:
          name: test-report
          path: app/build/reports/tests/
